language: node_js
dist: trusty
sudo: required
node_js: 7
install:
  - npm install bower -g
  - npm install
script:
  - bower install --production
  - npm run -s build
  - bower install
  - npm -s test
